#!/bin/bash

cd $(dirname $0)/..
zip_file="CC_submission_$(date +'%Y-%m-%dT%H-%M-%S')_$(whoami).zip"
find src -not -name '*.pyc' -not -name __pycache__ | xargs zip "$zip_file"
echo "Created zip file $zip_file"
